/* Bangla-first bilingual strings (07 §6 one-language-per-element rule).
 * BN is the content baseline for a borrower app; EN is the toggle. */
export type Lang = "bn" | "en";
export const STRINGS: Record<string, { en: string; bn: string }> = {
  "app.title": { en: "ULMS Borrower", bn: "ইউএলএমএস গ্রহীতা" },
  "nav.home": { en: "Home", bn: "হোম" },
  "nav.track": { en: "My Applications", bn: "আবেদন" },
  "nav.pay": { en: "Pay", bn: "পরিশোধ" },
  "nav.statements": { en: "Statements", bn: "স্টেটমেন্ট" },
  "nav.more": { en: "More", bn: "আরও" },
  "login.title": { en: "Welcome", bn: "স্বাগতম" },
  "login.mobile": { en: "Mobile number", bn: "মোবাইল নম্বর" },
  "login.sendOtp": { en: "Send code", bn: "কোড পাঠান" },
  "login.otp": { en: "SMS code", bn: "এসএমএস কোড" },
  "login.verify": { en: "Sign in", bn: "সাইন ইন" },
  "login.otpSent": { en: "Code sent — check your SMS", bn: "কোড পাঠানো হয়েছে — এসএমএস দেখুন" },
  "login.devCode": { en: "Dev OTP auto-filled — production delivers by SMS", bn: "ডেভ কোড স্বয়ংক্রিয় — প্রোডাকশনে এসএমএস আসবে" },
  "home.greeting": { en: "Hello", bn: "আসসালামু আলাইকুম" },
  "home.outstanding": { en: "Outstanding balance", bn: "বকেয়া পরিমাণ" },
  "home.emi": { en: "Monthly instalment", bn: "মাসিক কিস্তি" },
  "home.nextDue": { en: "Next due", bn: "পরবর্তী দেয়তারিখ" },
  "home.dpd": { en: "days past due", bn: "দিন অতিবাহিত" },
  "home.current": { en: "Your account is current", bn: "আপনার হিসাব চলতি আছে" },
  "home.noLoans": { en: "No loans yet — apply below", bn: "এখনো ঋণ নেই — নিচে আবেদন করুন" },
  "home.payNow": { en: "Pay now", bn: "এখনই পরিশোধ" },
  "track.title": { en: "My applications", bn: "আমার আবেদন" },
  "track.empty": { en: "No applications", bn: "কোনো আবেদন নেই" },
  "track.apply": { en: "Apply for a loan", bn: "ঋণের আবেদন" },
  "track.amount": { en: "Amount (৳ Lakh)", bn: "পরিমাণ (৳ লাখ)" },
  "track.submit": { en: "Submit application", bn: "আবেদন জমা দিন" },
  "pay.title": { en: "Make a payment", bn: "পরিশোধ করুন" },
  "pay.amount": { en: "Amount (৳)", bn: "পরিমাণ (৳)" },
  "pay.rail": { en: "Payment method", bn: "পরিশোধের মাধ্যম" },
  "pay.confirm": { en: "Confirm & pay", bn: "নিশ্চিত ও পরিশোধ" },
  "pay.redirect": { en: "Opening secure checkout…", bn: "নিরাপদ চেকআউট খোলা হচ্ছে…" },
  "pay.history": { en: "Payment history", bn: "পরিশোধের ইতিহাস" },
  "stmt.title": { en: "Statements", bn: "স্টেটমেন্ট" },
  "stmt.download": { en: "Download statement (CSV)", bn: "স্টেটমেন্ট ডাউনলোড (সিএসভি)" },
  "more.title": { en: "More", bn: "আরও" },
  "more.lang": { en: "Language", bn: "ভাষা" },
  "more.payoff": { en: "Early payoff calculator", bn: "আগাম পরিশোধ ক্যালকুলেটর" },
  "more.payoffExtra": { en: "Extra per month (৳)", bn: "অতিরিক্ত মাসিক (৳)" },
  "more.help": { en: "Help & support", bn: "সহায়তা" },
  "more.logout": { en: "Sign out", bn: "সাইন আউট" },
  "more.branch": { en: "Your branch: BR-001 · +880 2 5566 0000", bn: "আপনার শাখা: বিআর-০০১ · +৮৮০ ২ ৫৫৬৬ ০০০০" },
};
export function t(lang: Lang, key: string): string {
  const s = STRINGS[key];
  return s ? (lang === "bn" ? s.bn : s.en) : key;
}
