// Generates src/i18n/strings.generated.ts from docs/p5/i18n-catalog.json.
// The catalog's Bengali comes only from the validated prototype dictionaries
// (Front_end/js/i18n.js, i18n_data.js, nav_data.js) — never invented here.
// Run from apps/web: node scripts/gen-i18n.mjs   (after editing the catalog)
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = JSON.parse(readFileSync(resolve(here, "../../../docs/p5/i18n-catalog.json"), "utf-8"));
const out = `// GENERATED by scripts/gen-i18n.mjs from docs/p5/i18n-catalog.json — do not edit by hand.
// Source of the Bengali: the validated prototype dictionaries only (i18n.js,
// i18n_data.js, nav_data.js). Keys with bn:null await bank translation review.
export type BilingualString = { en: string; bn: string | null };
export const STRINGS: Record<string, BilingualString> = ${JSON.stringify(src, null, 2)} as const;
`;
writeFileSync(resolve(here, "../src/i18n/strings.generated.ts"), out, "utf-8");
console.log("wrote src/i18n/strings.generated.ts with", Object.keys(src).length, "keys");
